/* GENERATED by scripts/gen-resources.ts — do not hand-edit.

   A real article URL per tech Q&A item, for the one family that had
   nowhere to send you: no LeetCode number and no curated reading. Each URL
   was handed back by its own publisher's index for a published article, and
   every significant word of the question appears in the article title.
   Baeldung answers 403 to a crawler on every path, so these rest on the
   index rather than on a liveness check. Links rot — re-run the script
   rather than trusting this file forever.

   Items absent from this map fall back to a labelled search in lib/study.ts,
   which is honest about being a search.

   64 of 197 attempted items resolved.  */

const RESOURCES: Record<string, [string, string, string][]> = {
  'tq-api-1': [
    ['Baeldung', 'https://www.baeldung.com/java-enum-http-status', 'Java Enums With All HTTP Status Codes'],
  ],
  'tq-api-11': [
    ['Baeldung', 'https://www.baeldung.com/resilience4j-backoff-jitter', 'Better Retries with Exponential Backoff and Jitter'],
  ],
  'tq-api-12': [
    ['Baeldung', 'https://www.baeldung.com/spring-rest-timeout', 'Setting a Request Timeout for a Spring REST API'],
  ],
  'tq-api-13': [
    ['Baeldung', 'https://www.baeldung.com/java-spring-bind-custom-validation-message', 'Bind Custom Validation Message in Spring'],
  ],
  'tq-api-2': [
    ['Baeldung', 'https://www.baeldung.com/spring-data-webflux-pagination', 'Pagination in Spring Webflux and Spring Data Reactive'],
  ],
  'tq-api-3': [
    ['Baeldung', 'https://www.baeldung.com/rest-versioning', 'Versioning a REST API'],
  ],
  'tq-api-4': [
    ['Baeldung', 'https://www.baeldung.com/http-put-patch-difference-spring', 'HTTP PUT vs HTTP PATCH in a REST API'],
  ],
  'tq-boot-0': [
    ['Baeldung', 'https://www.baeldung.com/spring-boot-exclude-auto-configuration-test', 'Exclude Auto-Configuration Classes in Spring Boot Tests'],
  ],
  'tq-boot-10': [
    ['Baeldung', 'https://www.baeldung.com/spring-boot-web-server-shutdown', 'Web Server Graceful Shutdown in Spring Boot'],
  ],
  'tq-boot-2': [
    ['Baeldung', 'https://www.baeldung.com/cassandre-spring-boot-trading-bot', 'Build a Trading Bot with Cassandre Spring Boot Starter'],
  ],
  'tq-boot-4': [
    ['Baeldung', 'https://www.baeldung.com/spring-boot-enable-disable-embedded-tomcat', 'Enable or Disable Embedded Tomcat with Profile in Spring Boot'],
  ],
  'tq-boot-6': [
    ['Baeldung', 'https://www.baeldung.com/spring-boot-actuator-without-spring-boot', 'Spring Boot Actuator Without Spring Boot'],
  ],
  'tq-boot-7': [
    ['Baeldung', 'https://www.baeldung.com/spring-liveness-readiness-probes', 'Liveness and Readiness Probes in Spring Boot'],
  ],
  'tq-boot-9': [
    ['Baeldung', 'https://www.baeldung.com/spring-mvc-async-vs-webflux', 'Spring MVC Async vs Spring WebFlux'],
  ],
  'tq-conc-10': [
    ['Baeldung', 'https://www.baeldung.com/java-threadlocal', 'An Introduction to ThreadLocal in Java'],
  ],
  'tq-conc-12': [
    ['Baeldung', 'https://www.baeldung.com/java-producer-consumer-problem', 'Producer-Consumer Problem With Example in Java'],
  ],
  'tq-conc-14': [
    ['Baeldung', 'https://www.baeldung.com/java-synchronize-virtual-thread-no-pinning', 'Synchronize Virtual Thread Without Pinning'],
  ],
  'tq-conc-4': [
    ['Baeldung', 'https://www.baeldung.com/java-hashtable-vs-concurrenthashmap', 'Difference Between Hashtable and ConcurrentHashMap in Java'],
  ],
  'tq-conc-7': [
    ['Baeldung', 'https://www.baeldung.com/java-deadlock-livelock', 'Java Thread Deadlock and Livelock'],
  ],
  'tq-events-5': [
    ['Baeldung', 'https://www.baeldung.com/spring-security-async-principal-propagation', 'Spring Security Context Propagation with @Async'],
  ],
  'tq-java-0': [
    ['Baeldung', 'https://www.baeldung.com/java-string-immutable', 'Why String Is Immutable in Java?'],
  ],
  'tq-java-1': [
    ['Baeldung', 'https://www.baeldung.com/java-equals-hashcode-contracts', 'Java equals() and hashCode() Contracts'],
  ],
  'tq-java-10': [
    ['Baeldung', 'https://www.baeldung.com/java-checked-unchecked-exceptions', 'Checked and Unchecked Exceptions in Java'],
  ],
  'tq-java-13': [
    ['Baeldung', 'https://www.baeldung.com/java-comparator-comparable', 'Comparator and Comparable in Java'],
  ],
  'tq-java-4': [
    ['Baeldung', 'https://www.baeldung.com/java-arraylist-vs-linkedlist-vs-hashmap', 'ArrayList vs. LinkedList vs. HashMap in Java'],
  ],
  'tq-java-5': [
    ['Baeldung', 'https://www.baeldung.com/java-arraylist-include-string-arrays', 'How to Add String Arrays to ArrayList in Java'],
  ],
  'tq-java-6': [
    ['Baeldung', 'https://www.baeldung.com/java-string-constant-pool-heap-stack', 'Where Does Java’s String Constant Pool Live, the Heap or the Stack?'],
  ],
  'tq-java-7': [
    ['Baeldung', 'https://www.baeldung.com/java-gc-logging-to-file', 'Garbage Collection Logging to a File in Java'],
  ],
  'tq-java-9': [
    ['Baeldung', 'https://www.baeldung.com/java-final-finally-finalize', 'Differences Between Final, Finally and Finalize in Java'],
  ],
  'tq-jpa-0': [
    ['Baeldung', 'https://www.baeldung.com/jpa-hibernate-persistence-context', 'JPA/Hibernate Persistence Context'],
  ],
  'tq-jpa-10': [
    ['Baeldung', 'https://www.baeldung.com/jpa-cascade-remove-vs-orphanremoval', 'JPA CascadeType.REMOVE vs orphanRemoval'],
  ],
  'tq-jpa-13': [
    ['Baeldung', 'https://www.baeldung.com/jpa-pessimistic-locking', 'Pessimistic Locking in JPA'],
  ],
  'tq-jpa-16': [
    ['Baeldung', 'https://www.baeldung.com/hibernate-second-level-cache', 'Hibernate Second-Level Cache'],
  ],
  'tq-jpa-2': [
    ['Baeldung', 'https://www.baeldung.com/java-hibernate-entity-dirty-check', 'How Hibernate Dirty Checking Mechanism Works'],
  ],
  'tq-jpa-4': [
    ['Baeldung', 'https://www.baeldung.com/spring-data-jpa-save-saveandflush', 'Difference Between save() and saveAndFlush() in Spring Data JPA'],
  ],
  'tq-jpa-5': [
    ['Baeldung', 'https://www.baeldung.com/spring-hibernate-n1-problem', 'N+1 Problem in Hibernate and Spring Data JPA'],
  ],
  'tq-jpa-7': [
    ['Baeldung', 'https://www.baeldung.com/spring-open-session-in-view', 'A Guide to Spring’s Open Session in View'],
  ],
  'tq-jpa-9': [
    ['Baeldung', 'https://www.baeldung.com/jpa-cascade-types', 'Overview of JPA/Hibernate Cascade Types'],
  ],
  'tq-kafka-2': [
    ['Baeldung', 'https://www.baeldung.com/kafka-manage-consumer-groups', 'Manage Kafka Consumer Groups'],
  ],
  'tq-kafka-5': [
    ['Baeldung', 'https://www.baeldung.com/kafka-message-delivery-semantics', 'Message Delivery Semantics in Streaming Platforms'],
  ],
  'tq-kafka-6': [
    ['Baeldung', 'https://www.baeldung.com/java-jdbc-auto-commit', 'A Guide to Auto-Commit in JDBC'],
  ],
  'tq-kafka-9': [
    ['Baeldung', 'https://www.baeldung.com/java-kafka-consumer-lag', 'Monitor the Consumer Lag in Apache Kafka'],
  ],
  'tq-micro-4': [
    ['Baeldung', 'https://www.baeldung.com/devops-haproxy-api-gateway', 'Using HAProxy as an API Gateway for Routing and Rate Limiting'],
  ],
  'tq-micro-5': [
    ['Baeldung', 'https://www.baeldung.com/spring-boot-circuit-breaker-vs-retry', 'Difference Between Circuit Breaker and Retry in Spring Boot'],
  ],
  'tq-micro-7': [
    ['Baeldung', 'https://www.baeldung.com/kafka-producer-retries', 'Retries With Kafka Producer'],
  ],
  'tq-modern-3': [
    ['Baeldung', 'https://www.baeldung.com/java-optional-or-else-vs-or-else-get', 'Java Optional – orElse() vs orElseGet()'],
  ],
  'tq-modern-5': [
    ['Baeldung', 'https://www.baeldung.com/java-sealed-classes-interfaces', 'Sealed Classes and Interfaces in Java'],
  ],
  'tq-modern-8': [
    ['Baeldung', 'https://www.baeldung.com/java-text-blocks', 'Java Text Blocks'],
  ],
  'tq-modern-9': [
    ['Baeldung', 'https://www.baeldung.com/java-virtual-thread-vs-thread', 'Difference Between Thread and Virtual Thread in Java'],
  ],
  'tq-obs-1': [
    ['Baeldung', 'https://www.baeldung.com/spring-boot-structured-logging', 'Structured Logging in Spring Boot'],
  ],
  'tq-obs-13': [
    ['Baeldung', 'https://www.baeldung.com/liquibase-rollback', 'Introduction to Liquibase Rollback'],
  ],
  'tq-obs-14': [
    ['Baeldung', 'https://www.baeldung.com/java-unleash-feature-flags', 'Implement Feature Flags in Java With Unleash'],
  ],
  'tq-obs-5': [
    ['Baeldung', 'https://www.baeldung.com/spring-test-pyramid-practical-example', 'Practical Application of Test Pyramid in Spring-based Microservice'],
  ],
  'tq-obs-6': [
    ['Baeldung', 'https://www.baeldung.com/java-mockito-constructors-unit-testing', 'How to Mock Constructors for Unit Testing using Mockito'],
  ],
  'tq-obs-7': [
    ['Baeldung', 'https://www.baeldung.com/java-quarkus-testcontainers', 'Testing a Quarkus Application Using Testcontainers for Service Dependencies'],
  ],
  'tq-pg-12': [
    ['Baeldung', 'https://www.baeldung.com/cassandra-replication-partitioning', 'Replication Strategies and Partitioning in Cassandra'],
  ],
  'tq-pg-15': [
    ['Baeldung', 'https://www.baeldung.com/mongodb-upsert', 'Guide to Upsert in MongoDB'],
  ],
  'tq-pg-8': [
    ['Baeldung', 'https://www.baeldung.com/java-deadlock-livelock', 'Java Thread Deadlock and Livelock'],
  ],
  'tq-pg-9': [
    ['Baeldung', 'https://www.baeldung.com/spring-oracle-connection-pooling', 'Oracle Connection Pooling With Spring'],
  ],
  'tq-spring-0': [
    ['Baeldung', 'https://www.baeldung.com/inversion-control-and-dependency-injection-in-spring', 'Intro to Inversion of Control and Dependency Injection with Spring'],
  ],
  'tq-spring-1': [
    ['Baeldung', 'https://www.baeldung.com/spring-prototype-bean-runtime-arguments', 'Create Spring Prototype Scope Bean with Runtime Arguments'],
  ],
  'tq-spring-10': [
    ['Baeldung', 'https://www.baeldung.com/circular-dependencies-in-spring', 'Circular Dependencies in Spring'],
  ],
  'tq-spring-6': [
    ['Baeldung', 'https://www.baeldung.com/spring-transactional-propagation-isolation', 'Transaction Propagation and Isolation in Spring @Transactional'],
  ],
  'tq-spring-8': [
    ['Baeldung', 'https://www.baeldung.com/spring-transactional-propagation-isolation', 'Transaction Propagation and Isolation in Spring @Transactional'],
  ],
};

export default RESOURCES;
