/* Tech — 13 modules, triggers, practice problems, reading
   Moved VERBATIM from legacy/data.js — this file is content, not code.
   Edit this to change the plan; gen-sheet.js regenerates the markdown sheet
   from it, so the sheet cannot drift.

   Progress keys are content-addressed, so APPENDING to any list is safe;
   reordering within a list remaps that list's saved progress. */
/* eslint-disable */
// @ts-nocheck

const PLAN: any = {};

PLAN.tech = [

{id:'java', n:1, name:'Java core & collections', phase:1, hrs:9,
 asked:[
  'Walk me through what happens when you put an object in a HashMap.',
  'Why is String immutable?',
  'ArrayList or LinkedList here, and why?',
  'How would you find a memory leak in production?'
 ],
 code:[
  ['equals / hashCode done correctly',
   ['@Override public boolean equals(Object o) {',
    '    if (this == o) return true;',
    '    if (!(o instanceof Order other)) return false;   // pattern matching, Java 16+',
    '    return Objects.equals(id, other.id);             // ONLY immutable identity fields',
    '}',
    '@Override public int hashCode() { return Objects.hash(id); }'],
   'The contract: equal objects MUST have equal hashcodes. Use only fields that never change after construction, or the object gets lost in its own HashMap.'],
  ['Safe iteration and removal',
   ['// WRONG - ConcurrentModificationException',
    'for (Order o : orders) if (o.isCancelled()) orders.remove(o);',
    '',
    '// right, single-threaded',
    'orders.removeIf(Order::isCancelled);',
    '',
    '// right, explicit iterator',
    'Iterator<Order> it = orders.iterator();',
    'while (it.hasNext()) if (it.next().isCancelled()) it.remove();'],
   'removeIf is the modern answer. Knowing WHY the enhanced for-loop throws is the interview.']
 ],
 qa:[
  ['Why is String immutable?','Security (class loading, file paths cannot be mutated after a check), hashcode caching, safe sharing in the string pool, and thread safety with no synchronisation.','Then how does StringBuilder differ, and when does the compiler use it for you? (String concatenation in a loop is the classic waste.)'],
  ['The equals/hashCode contract','Equal objects must have equal hashcodes; unequal objects may collide. Override both or neither.','You put a mutable object in a HashSet then mutate the field used in hashCode. What happens? => the bucket no longer matches, contains() returns false, and the object is unreachable but still consuming memory.'],
  ['HashMap internals','Array of buckets; each bucket a linked list; treeified into a red-black tree at 8 nodes (Java 8+); resize doubles capacity at load factor 0.75 and rehashes.','Why treeify? => it caps worst-case lookup at O(log n) and defends against hash-collision denial-of-service attacks.'],
  ['HashMap vs LinkedHashMap vs TreeMap','Unordered / insertion or access order / sorted by comparator.','Which one gives you an LRU cache almost for free? => LinkedHashMap with accessOrder=true and removeEldestEntry overridden.'],
  ['ArrayList vs LinkedList','Contiguous array with O(1) random access and cache-friendly iteration, versus node chasing with O(1) insert once you already hold the node.','Why does LinkedList lose even for middle insertion? => you still pay O(n) to walk there, and every node is a cache miss.'],
  ['Array vs ArrayList','Fixed size, can hold primitives, covariant. ArrayList grows, boxes primitives, is invariant with generics.','Why does new List<int>() not compile? => generics do not accept primitives; erasure requires reference types.'],
  ['Heap vs stack','Objects and their fields on the heap; frames, locals and references on the stack. Each thread has its own stack.','Where does a String literal live? => the string pool, which sits in the heap since Java 7.'],
  ['Garbage collection','Generational hypothesis: most objects die young. Young generation collected often and cheaply; old generation rarely and expensively. G1 splits the heap into regions and collects the emptiest first.','What is a stop-the-world pause and how do you reduce it? => smaller heaps, region-based collectors, avoiding huge object graphs, and tuning pause targets.'],
  ['Memory leak in a garbage-collected language','Unbounded caches, listeners that are never deregistered, ThreadLocal in a pooled thread, static collections that only grow, and unclosed resources.','How would you find one? => heap dump, then the dominator tree in a tool like Eclipse MAT to find who is holding the retained set.'],
  ['final, finally, finalize','A binding or class that cannot change / a block that always runs / a deprecated pre-collection hook you must never use.','Does finally always run? => not on System.exit, a JVM crash, or an infinite loop in try. And a return in finally silently swallows exceptions.'],
  ['Checked vs unchecked exceptions','Checked = the caller can plausibly recover. Unchecked = a programming error.','Why do many modern codebases avoid checked exceptions? => they leak through abstraction layers, do not compose with lambdas, and get swallowed with empty catch blocks.'],
  ['Generics and type erasure','Generic types exist at compile time only; the runtime sees raw types plus synthetic casts.','Why can you not write new T[]? => the runtime has no idea what T is, so it cannot create the array.'],
  ['== vs equals for boxed types','== compares references. Integer caches -128 to 127, so small values appear to work.','Why does Integer a = 128, b = 128; a == b evaluate false? => outside the cache range, two distinct objects.'],
  ['Comparable vs Comparator','Natural ordering inside the class versus an external ordering strategy.','Your comparator is inconsistent with equals. What breaks? => TreeSet and TreeMap silently treat distinct objects as duplicates.'],
  ['String pool and interning','Literals are pooled; new String() is not.','What does intern() do, and why is it usually a mistake? => forces pooling, and on hot paths it becomes a contended bottleneck.']
 ],
 traps:[
  'Overriding equals but not hashCode. Interviewers check this constantly.',
  'Using a mutable field in hashCode.',
  'Concatenating strings in a loop instead of StringBuilder.',
  'Assuming ArrayList.remove(int) and remove(Object) do the same thing on a List<Integer>. They do not.'
 ]},

{id:'modern', n:2, name:'Modern Java (8 to 21)', phase:1, hrs:5,
 asked:[
  'Rewrite this loop with the Streams API.',
  'When is a parallel stream a bad idea?',
  'What are records for?',
  'How do you avoid null without Optional everywhere?'
 ],
 code:[
  ['Streams: grouping and summarising',
   ['Map<Status, List<Order>> byStatus = orders.stream()',
    '        .collect(Collectors.groupingBy(Order::getStatus));',
    '',
    'Map<Status, BigDecimal> totals = orders.stream()',
    '        .collect(Collectors.groupingBy(Order::getStatus,',
    '                 Collectors.reducing(BigDecimal.ZERO, Order::getAmount, BigDecimal::add)));',
    '',
    'Optional<Order> largest = orders.stream()',
    '        .max(Comparator.comparing(Order::getAmount));'],
   'groupingBy with a downstream collector is the single most useful thing in the Streams API, and the one candidates most often fumble.'],
  ['Record as a DTO or value object',
   ['public record Money(BigDecimal amount, Currency currency) {',
    '    public Money {',
    '        if (amount.signum() < 0) throw new IllegalArgumentException("negative");',
    '    }',
    '    public Money plus(Money other) {',
    '        if (!currency.equals(other.currency)) throw new IllegalArgumentException("mixed currency");',
    '        return new Money(amount.add(other.amount), currency);',
    '    }',
    '}'],
   'Records give you a final class, equals, hashCode, toString and accessors. The compact constructor is where validation goes. Ideal for DTOs and value objects; wrong for JPA entities, which need a no-arg constructor and mutability.']
 ],
 qa:[
  ['Streams: lazy or eager?','Lazy. Intermediate operations build a pipeline; nothing runs until a terminal operation.','A stream with no terminal operation - what happens? => nothing at all, and it is a silent bug.'],
  ['When is a parallel stream slower?','Small collections, cheap per-element work, non-splittable sources like LinkedList, or any blocking IO inside the lambda.','Which thread pool does it use? => the common ForkJoinPool, shared process-wide, so one slow parallel stream starves everything else.'],
  ['Optional: correct use','A return type for a value that may legitimately be absent.','Why not as a field or a method parameter? => it is not Serializable, it adds an allocation, and an overload or null check is clearer for parameters.'],
  ['orElse vs orElseGet','orElse always evaluates its argument; orElseGet only on absence.','So what is wrong with orElse(expensiveCall())? => the expensive call runs even when the value is present.'],
  ['Records vs Lombok @Data','Records are a language feature: final, immutable, no setters. @Data generates mutable boilerplate.','Can you use a record as a JPA entity? => no. JPA needs a no-arg constructor and non-final fields for proxies.'],
  ['Sealed interfaces','Restricts which types may implement, so the compiler can check exhaustiveness in a switch.','Where does that help? => modelling a closed set of states or events, with no default branch hiding a missing case.'],
  ['var','Local type inference; the type is still static and fixed.','When does it hurt readability? => when the right-hand side does not make the type obvious.'],
  ['CompletableFuture vs Stream','Async composition versus data transformation. Different axes.','How do you run 10 HTTP calls in parallel and collect the results? => a list of CompletableFutures, then allOf(...).join(), then map to join each.'],
  ['Text blocks','Multi-line string literals. Useful for SQL and JSON in tests.','Any runtime cost? => none, resolved at compile time.'],
  ['Virtual threads (21)','Lightweight threads scheduled by the JVM; blocking is cheap so thread-per-request scales.','When do they NOT help? => CPU-bound work, and code pinned by synchronized blocks holding the carrier thread.']
 ],
 traps:[
  'Side effects inside a stream lambda (mutating an external list). Use a collector.',
  'Reusing a stream after a terminal operation. It throws.',
  'Optional.get() without isPresent. That is just a nullcheck with extra steps.',
  'Parallel streams on anything doing IO.'
 ]},

{id:'conc', n:3, name:'Concurrency', phase:1, hrs:12,
 note:'JPM and Amex go deep here. Your custom event-driven components make this a natural question, so expect it.',
 asked:[
  'What is the difference between volatile and synchronized?',
  'How do you size a thread pool?',
  'Write a thread-safe counter. Now make it faster.',
  'Reproduce a deadlock, then fix it.'
 ],
 code:[
  ['Thread pool with a bounded queue and a rejection policy',
   ['@Bean("taskExecutor")',
    'public ThreadPoolTaskExecutor taskExecutor() {',
    '    ThreadPoolTaskExecutor ex = new ThreadPoolTaskExecutor();',
    '    ex.setCorePoolSize(8);',
    '    ex.setMaxPoolSize(16);',
    '    ex.setQueueCapacity(500);                       // BOUNDED - unbounded means OOM',
    '    ex.setThreadNamePrefix("evt-");                 // shows up in thread dumps',
    '    ex.setRejectedExecutionHandler(',
    '        new ThreadPoolExecutor.CallerRunsPolicy()); // backpressure onto the caller',
    '    ex.setWaitForTasksToCompleteOnShutdown(true);',
    '    ex.setAwaitTerminationSeconds(30);',
    '    return ex;',
    '}'],
   'Three interview points in one bean: the queue is bounded, the rejection policy applies backpressure instead of dropping, and shutdown drains. The default Spring executor does none of this.'],
  ['Deadlock, and the fix',
   ['// DEADLOCK: two threads take the locks in opposite order',
    'void transfer(Account a, Account b, BigDecimal amt) {',
    '    synchronized (a) { synchronized (b) { a.debit(amt); b.credit(amt); } }',
    '}',
    '',
    '// FIX: impose a global lock ordering',
    'void transfer(Account a, Account b, BigDecimal amt) {',
    '    Account first  = a.getId() < b.getId() ? a : b;',
    '    Account second = a.getId() < b.getId() ? b : a;',
    '    synchronized (first) { synchronized (second) { a.debit(amt); b.credit(amt); } }',
    '}'],
   'Lock ordering is the standard answer. The alternative is tryLock with a timeout and retry. Be able to write both.'],
  ['Parallel calls with CompletableFuture',
   ['List<CompletableFuture<Quote>> futures = vendors.stream()',
    '    .map(v -> CompletableFuture.supplyAsync(() -> client.quote(v), taskExecutor)',
    '                 .orTimeout(2, TimeUnit.SECONDS)',
    '                 .exceptionally(ex -> Quote.unavailable(v)))',
    '    .toList();',
    '',
    'CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();',
    'List<Quote> quotes = futures.stream().map(CompletableFuture::join).toList();'],
   'Note the explicit executor (never the common pool for IO), the per-call timeout, and the fallback. Without those three this pattern hangs your request thread.']
 ],
 qa:[
  ['volatile vs synchronized','volatile gives visibility and ordering, no atomicity. synchronized gives mutual exclusion plus visibility.','Is count++ safe on a volatile int? => no. It is read-modify-write, three operations. Use AtomicInteger.'],
  ['The happens-before relationship','The JMM rule that makes one thread writes visible to another: unlock before lock, volatile write before volatile read, thread start, thread join.','Why is double-checked locking broken without volatile? => the reference can be published before the constructor finishes, so another thread sees a partially built object.'],
  ['Thread pool sizing','CPU-bound is roughly cores + 1. IO-bound is roughly cores x (1 + waitTime/serviceTime).','What if the queue is unbounded and producers outpace consumers? => memory grows until OutOfMemoryError. Bound the queue and choose a rejection policy.'],
  ['ExecutorService shutdown','shutdown stops accepting and drains; shutdownNow interrupts; awaitTermination blocks for the drain.','Your application will not exit. Why? => non-daemon pool threads still alive because nothing called shutdown.'],
  ['ConcurrentHashMap','Locks at the bin level using CAS plus synchronized on the bin head, not the whole map.','Is if (map.get(k) == null) map.put(k, v) safe? => no, it is check-then-act. Use computeIfAbsent or putIfAbsent.'],
  ['computeIfAbsent pitfall','Atomic per key, but the mapping function must not modify the same map.','What happens if it does? => in Java 9+ a ConcurrentModificationException; before that, a corrupted map or an infinite loop.'],
  ['CompletableFuture composition','thenApply transforms; thenCompose flattens a nested future; thenCombine joins two.','Which executor runs your callback if you do not pass one? => the one that completed the previous stage, or the common ForkJoinPool. Always pass your own for IO.'],
  ['Deadlock','Four Coffman conditions: mutual exclusion, hold and wait, no pre-emption, circular wait. Break any one.','How do you detect one in production? => a thread dump shows "Found one Java-level deadlock" explicitly.'],
  ['Livelock and starvation','Threads keep responding to each other and make no progress; or a thread never gets scheduled.','How is livelock different from deadlock? => the threads are running, which makes it harder to spot.'],
  ['Optimistic vs pessimistic locking','Compare-and-set or a version column, versus holding a lock.','Which for a high-contention seat booking, and why? => pessimistic, or an atomic conditional update. Optimistic retries thrash under contention.'],
  ['ThreadLocal','Per-thread storage. Must be removed in a pooled thread.','What leaks if you do not? => the value stays bound to the pooled thread and is visible to the next unrelated request. A correctness bug as well as a leak.'],
  ['Atomics and LongAdder','AtomicInteger is a CAS loop. LongAdder spreads across cells and sums on read.','When does LongAdder beat AtomicLong? => high write contention with infrequent reads, like a metrics counter.'],
  ['Producer-consumer','BlockingQueue with bounded capacity gives you backpressure for free.','Bounded or unbounded, and what breaks with each? => unbounded risks OOM; bounded blocks the producer, which is usually what you want.'],
  ['synchronized method vs block','Method locks this (or the class for static); a block locks whatever monitor you name.','Can two synchronized methods on the same object run concurrently? => no, they share the same monitor.'],
  ['Virtual threads (Java 21)','Cheap, blocking-friendly, scheduled on carrier threads.','What is pinning? => a virtual thread inside a synchronized block cannot unmount, so it holds the carrier. Use ReentrantLock instead.'],
  ['Immutability as a concurrency strategy','No shared mutable state means no synchronisation needed.','What is the cheapest way to make a class thread-safe? => make it immutable. Say this before reaching for locks.']
 ],
 traps:[
  'Unbounded queues in thread pools. The classic production OutOfMemoryError.',
  'ThreadLocal not removed in a pooled thread - leaks data across requests.',
  'Using the common ForkJoinPool for blocking IO.',
  'Assuming synchronized collections are enough for compound operations. Collections.synchronizedList still needs external locking for check-then-act.'
 ]},

{id:'spring', n:4, name:'Spring core & DI', phase:1, hrs:9,
 asked:[
  'How does dependency injection actually work in Spring?',
  'Why does @Transactional not work when I call the method from the same class?',
  'Explain the bean lifecycle.',
  'Constructor or field injection, and why?'
 ],
 code:[
  ['Constructor injection, the way it should be written',
   ['@Service',
    'public class OrderService {',
    '    private final OrderRepository repo;',
    '    private final PaymentClient payments;',
    '',
    '    // no @Autowired needed since Spring 4.3 for a single constructor',
    '    public OrderService(OrderRepository repo, PaymentClient payments) {',
    '        this.repo = repo;',
    '        this.payments = payments;',
    '    }',
    '}'],
   'Final fields, immutable, trivially unit-testable with new OrderService(mock, mock), and circular dependencies fail loudly at startup instead of silently at runtime.'],
  ['The self-invocation trap and three fixes',
   ['@Service',
    'public class OrderService {',
    '',
    '    public void placeAll(List<Order> orders) {',
    '        orders.forEach(this::place);   // BUG: bypasses the proxy, NO transaction',
    '    }',
    '',
    '    @Transactional',
    '    public void place(Order o) { ... }',
    '}',
    '',
    '// FIX 1 - inject self (Spring resolves the proxy)',
    '@Autowired @Lazy private OrderService self;',
    'orders.forEach(self::place);',
    '',
    '// FIX 2 - move the transactional method to another bean (preferred)',
    '',
    '// FIX 3 - programmatic',
    'transactionTemplate.executeWithoutResult(status -> place(o));'],
   'THE most-asked Spring question. AOP works through a proxy; this.method() never touches it. Fix 2 is the one to name first because it fixes the design, not just the symptom.'],
  ['Transaction propagation that actually matters',
   ['@Transactional                                     // joins the caller transaction',
    'public void placeOrder(Order o) {',
    '    repo.save(o);',
    '    audit.record(o);      // REQUIRES_NEW - commits even if placeOrder rolls back',
    '}',
    '',
    '@Transactional(propagation = Propagation.REQUIRES_NEW)',
    'public void record(Order o) { auditRepo.save(new AuditEntry(o)); }'],
   'REQUIRES_NEW suspends the outer transaction and starts its own on a separate connection. Audit logging is the canonical legitimate use. It also means you now hold two connections, which is how pools get exhausted.']
 ],
 qa:[
  ['Inversion of control','The container owns construction and wiring; your class declares what it needs.','Constructor or field injection? => constructor: immutability, testability without reflection, and fail-fast on cycles.'],
  ['Bean scopes','singleton (default, one per context), prototype (new each injection), request, session.','A singleton bean holding mutable state - what happens? => shared across every request thread. Either make it stateless or synchronise.'],
  ['Bean lifecycle','instantiate, populate dependencies, *Aware callbacks, BeanPostProcessor before, @PostConstruct, BeanPostProcessor after, ready, @PreDestroy.','Where would you hook to modify every bean of a type? => a BeanPostProcessor. That is also how @Transactional and @Async wrap your beans.'],
  ['@Component vs @Bean','Class-level, found by component scan, versus a factory method inside @Configuration.','How do you register a bean from a third-party library you cannot annotate? => @Bean in a @Configuration class.'],
  ['AOP and proxies','JDK dynamic proxy when the bean implements an interface, CGLIB subclass otherwise. Advice wraps the join point.','Why does the aspect not fire on a private method or a self-invocation? => the call never leaves the object, so the proxy is not involved.'],
  ['@Transactional self-invocation','this.method() bypasses the proxy, so no transaction, no retry, no cache.','How do you fix it? => move the method to another bean (best), self-inject with @Lazy, or use TransactionTemplate.'],
  ['Propagation','REQUIRED joins or creates; REQUIRES_NEW suspends and starts a new one; NESTED uses a savepoint; MANDATORY throws if none exists.','The outer transaction rolls back - does the REQUIRES_NEW inner also roll back? => no, it already committed independently.'],
  ['Rollback rules','Rolls back on RuntimeException and Error by default; checked exceptions need rollbackFor.','You caught the exception inside the method - does it still roll back? => no. The proxy never sees it. This silently loses data.'],
  ['Isolation','READ_COMMITTED is the Postgres default; REPEATABLE_READ prevents non-repeatable reads; SERIALIZABLE prevents phantoms.','Give a concrete anomaly each level allows.'],
  ['readOnly = true','A hint: Hibernate skips dirty checking and the driver may route to a replica.','Does it prevent writes? => not reliably. It is an optimisation, not a guarantee.'],
  ['Circular dependencies','Constructor cycles fail at startup; setter or @Lazy can break them.','Why is failing the RIGHT behaviour? => a cycle is a design smell. Spring Boot 2.6+ disallows it by default.'],
  ['@Qualifier and @Primary','Disambiguate when several beans satisfy one type.','Two implementations of an interface and no qualifier - what happens? => NoUniqueBeanDefinitionException at startup.'],
  ['@Profile and conditional beans','Register beans only under a profile or a condition.','How do you swap a real client for a stub in tests? => a @Profile("test") bean, or @TestConfiguration.'],
  ['Spring MVC request flow','DispatcherServlet, HandlerMapping, HandlerAdapter, your controller, then a message converter or view resolver.','Where does @ControllerAdvice fit? => it wraps handler invocation to translate exceptions into responses centrally.'],
  ['@ControllerAdvice','Centralised exception handling and response shaping.','Why is it better than try/catch in every controller? => one error contract, no duplication, and it also catches exceptions from validation and converters.']
 ],
 traps:[
  'Self-invocation silently disabling @Transactional, @Async, @Cacheable and @Retryable.',
  'Catching an exception inside a transactional method and expecting a rollback.',
  'Field injection, which hides cycles and makes unit tests need a Spring context.',
  'Mutable state in a singleton bean.'
 ]},

{id:'boot', n:5, name:'Spring Boot & configuration', phase:1, hrs:5,
 asked:[
  'How does auto-configuration decide what to configure?',
  'How do you override an auto-configured bean?',
  'How do you inject secrets without putting them in the image?',
  'What does Actuator expose, and what must never be public?'
 ],
 code:[
  ['Typed configuration with validation',
   ['@ConfigurationProperties(prefix = "payments")',
    '@Validated',
    'public record PaymentProps(',
    '        @NotBlank String apiUrl,',
    '        @Positive int timeoutMs,',
    '        @DefaultValue("3") int maxRetries) {}',
    '',
    '// application.yml',
    '// payments:',
    '//   api-url: https://...',
    '//   timeout-ms: 2000'],
   'Typed, validated at startup, and a bad config fails the deploy instead of failing the first request at 3am. Far better than scattering @Value strings.'],
  ['Health checks mapped to Kubernetes probes',
   ['management:',
    '  endpoint:',
    '    health:',
    '      probes:',
    '        enabled: true          # exposes /health/liveness and /health/readiness',
    '  endpoints:',
    '    web:',
    '      exposure:',
    '        include: health,info,prometheus     # NOT env, NOT heapdump',
    '',
    'server:',
    '  shutdown: graceful           # drain in-flight requests',
    'spring:',
    '  lifecycle:',
    '    timeout-per-shutdown-phase: 25s'],
   'Liveness must not check downstreams or a slow database takes your pods down in a restart loop. Readiness should. Graceful shutdown plus a preStop hook is what actually gives zero-downtime rollouts.']
 ],
 qa:[
  ['Auto-configuration','@EnableAutoConfiguration loads candidates from AutoConfiguration.imports, each guarded by @ConditionalOnClass, @ConditionalOnMissingBean, @ConditionalOnProperty.','How do you stop one applying? => exclude it, or simply define your own bean, since most are @ConditionalOnMissingBean.'],
  ['Debugging auto-configuration','Run with --debug for the condition evaluation report showing what matched and what did not.','A bean you expected is missing. What is your first move? => read that report before changing any code.'],
  ['Starters','Curated transitive dependency sets. No code of their own.','What is actually in spring-boot-starter-web? => Spring MVC, Jackson, validation, and embedded Tomcat.'],
  ['Config precedence','Command line, then OS env, then application-{profile}.yml, then application.yml, then defaults.','How do you inject a secret without baking it into the image? => environment variable from a Kubernetes Secret, or a mounted file, never the jar.'],
  ['Profiles','@Profile on beans, spring.profiles.active to select.','How do your Kubernetes manifests set it? => SPRING_PROFILES_ACTIVE as an env var. Relaxed binding maps it automatically.'],
  ['Relaxed binding','api-url, api_url, API_URL and apiUrl all bind to the same property.','Why does that matter in containers? => environment variables cannot contain dots or dashes.'],
  ['Actuator','/health, /info, /metrics, /prometheus, /env, /threaddump, /heapdump.','Which must never be public? => env, heapdump and threaddump leak secrets and internals. Bind Actuator to a separate management port.'],
  ['Liveness vs readiness in Boot','Health groups map to the two Kubernetes probes.','What must liveness NOT check? => downstream dependencies. A slow database would restart every pod at once.'],
  ['Embedded server and thread model','Tomcat by default, thread per request, default 200 threads.','How many concurrent requests can it handle, and what do you tune? => server.tomcat.threads.max, and remember every thread also holds a DB connection under load.'],
  ['WebFlux vs MVC','Event loop and backpressure versus thread per request.','When is WebFlux the wrong choice? => any blocking JDBC in the chain. One blocking call poisons the event loop.'],
  ['Graceful shutdown','Stop accepting, drain in-flight, then exit.','How does that interact with a rolling update? => needs a preStop sleep so the Service stops routing before the process starts draining, plus a long enough terminationGracePeriodSeconds.'],
  ['@SpringBootTest vs slices','Full context versus @WebMvcTest or @DataJpaTest.','Why prefer a slice? => seconds instead of minutes, and a failure points at one layer.']
 ],
 traps:[
  'Exposing all Actuator endpoints. management.endpoints.web.exposure.include=* in production is a real breach.',
  'Liveness probes that call the database.',
  'Secrets in application.yml committed to git.',
  'No graceful shutdown, so every deploy drops in-flight requests.'
 ]}

];


PLAN.tech = PLAN.tech.concat([

{id:'events', n:6, name:'Spring event-driven & async', phase:1, hrs:9,
 note:'YOUR DAILY WORK. You build custom event-driven components in Spring Boot, so expect an interviewer to pull hard on this thread. It is also the bridge to the Kafka module: the same problems, solved in-process first.',
 asked:[
  'You said your components are event-driven. Show me how that works.',
  'How do you publish an event only after the transaction commits?',
  'What happens to an exception thrown inside an @Async method?',
  'When would you move from Spring events to Kafka?'
 ],
 code:[
  ['Publishing and handling an in-process event',
   ['// 1. the event - a record, immutable, past tense name',
    'public record OrderPlaced(String orderId, BigDecimal amount, Instant at) {}',
    '',
    '// 2. publish',
    '@Service',
    '@RequiredArgsConstructor',
    'public class OrderService {',
    '    private final ApplicationEventPublisher events;',
    '',
    '    @Transactional',
    '    public void place(Order order) {',
    '        repo.save(order);',
    '        events.publishEvent(new OrderPlaced(order.getId(), order.getAmount(), Instant.now()));',
    '    }',
    '}',
    '',
    '// 3. handle',
    '@Component',
    'public class InvoiceListener {',
    '    @EventListener',
    '    public void on(OrderPlaced e) { invoices.create(e.orderId()); }',
    '}'],
   'By default @EventListener is SYNCHRONOUS and runs in the publisher thread, inside the same transaction. That surprises people: publishEvent is a method call, not a queue.'],
  ['@TransactionalEventListener - the one that matters',
   ['@Component',
    'public class EmailListener {',
    '',
    '    // runs ONLY after the transaction commits successfully',
    '    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)',
    '    public void on(OrderPlaced e) {',
    '        mailer.sendConfirmation(e.orderId());',
    '    }',
    '',
    '    // and the compensating side',
    '    @TransactionalEventListener(phase = TransactionPhase.AFTER_ROLLBACK)',
    '    public void onFailure(OrderPlaced e) {',
    '        metrics.increment("order.failed");',
    '    }',
    '}'],
   'Without AFTER_COMMIT you email the customer, then the transaction rolls back, and you have confirmed an order that does not exist. This is the single most valuable annotation in the module. Note the trap: a plain @Transactional handler at AFTER_COMMIT will NOT persist, because the transaction is already finished - you need REQUIRES_NEW.'],
  ['Async handling with a real executor',
   ['@Configuration',
    '@EnableAsync',
    'public class AsyncConfig implements AsyncConfigurer {',
    '',
    '    @Override public Executor getAsyncExecutor() { return taskExecutor(); }',
    '',
    '    // exceptions in void @Async methods are otherwise SILENTLY SWALLOWED',
    '    @Override public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {',
    '        return (ex, method, params) ->',
    '            log.error("async failure in {}", method.getName(), ex);',
    '    }',
    '}',
    '',
    '@Component',
    'public class ReportListener {',
    '    @Async("taskExecutor")',
    '    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)',
    '    public void on(OrderPlaced e) { reports.rebuild(e.orderId()); }',
    '}'],
   'Three things candidates miss: @Async needs @EnableAsync; a void @Async method swallows exceptions unless you register the handler; and the async thread has NO transaction, NO security context and NO MDC unless you propagate them.'],
  ['The outbox - when losing an event is not acceptable',
   ['@Transactional',
    'public void place(Order order) {',
    '    repo.save(order);',
    '    outbox.save(new OutboxEvent("OrderPlaced", toJson(order)));  // SAME transaction',
    '}',
    '',
    '@Scheduled(fixedDelay = 1000)',
    '@Transactional',
    'public void relay() {',
    '    for (OutboxEvent e : outbox.findUnpublished(100)) {',
    '        broker.publish(e.type(), e.payload());   // at-least-once',
    '        e.markPublished();',
    '    }',
    '}'],
   'In-process events die with the JVM. If the process crashes between commit and handler, the event is gone forever and nothing will ever retry it. The outbox makes the event as durable as the row. This is the answer to "what happens if the service crashes mid-handler".']
 ],
 qa:[
  ['How does publishEvent actually work?','ApplicationEventMulticaster looks up listeners by event type and invokes them. By default synchronously, on the caller thread, inside the caller transaction.','So is it a queue? => no. It is an in-process observer pattern. Nothing is persisted and nothing is retried.'],
  ['@EventListener vs @TransactionalEventListener','The first fires when publishEvent is called; the second binds to a transaction phase.','You email the customer from a plain @EventListener and the transaction then rolls back. What did the customer get? => a confirmation for an order that does not exist.'],
  ['The transaction phases','BEFORE_COMMIT, AFTER_COMMIT (default), AFTER_ROLLBACK, AFTER_COMPLETION.','Your AFTER_COMMIT handler writes to the database and nothing is saved. Why? => the transaction is already committed, so there is no active one. Use @Transactional(propagation = REQUIRES_NEW).'],
  ['@Async requirements','@EnableAsync plus a proxied call from another bean.','Why does calling an @Async method from within the same class run synchronously? => self-invocation. Same proxy problem as @Transactional.'],
  ['@Async exception handling','A method returning void swallows exceptions unless you register an AsyncUncaughtExceptionHandler. A method returning CompletableFuture surfaces them on join.','Which return type should you prefer, and why? => CompletableFuture, so failures are visible to the caller.'],
  ['Context propagation','The async thread has no transaction, no SecurityContext and no MDC by default.','How does your correlation id survive the hop? => a TaskDecorator that copies the MDC onto the worker thread. Without it your logs lose the trace id at the async boundary.'],
  ['Ordering listeners','@Order or Ordered on the listener.','Should you rely on listener ordering? => no. Order-dependent handlers mean the events are really a workflow, and should be modelled as one.'],
  ['Conditional listeners','@EventListener(condition = "#e.amount > 1000") using SpEL.','Why is that risky? => the logic is in a string, unchecked by the compiler and invisible to refactoring.'],
  ['Failure inside a synchronous listener','It propagates to the publisher and rolls back the transaction.','Is that good or bad? => it depends. A failing email should not roll back an order. That is the argument for AFTER_COMMIT plus async.'],
  ['What happens if the JVM dies mid-handler?','The event is lost. There is no persistence and no redelivery.','So how do you make it durable? => the outbox pattern, or a real broker. This is exactly the gap Kafka fills.'],
  ['Spring events vs Kafka','In-process, synchronous by default, no durability, single JVM. Kafka is durable, replayable, cross-process, with consumer groups and per-key ordering.','When do you move? => when another service needs the event, when you need replay, or when losing an event is unacceptable.'],
  ['@Scheduled in a multi-instance deployment','Every instance runs it. Three pods means three executions.','How do you fix it? => a distributed lock such as ShedLock, or move the job to a single leader.'],
  ['Backpressure in an async pipeline','A bounded queue plus CallerRunsPolicy pushes back onto the producer.','What does an unbounded queue give you? => the appearance of working, until an OutOfMemoryError.'],
  ['Testing event-driven code','ApplicationEvents in @RecordApplicationEvents, or a test listener capturing published events.','How do you test an AFTER_COMMIT listener? => it will not fire in a rolled-back test transaction. Use @Commit or TestTransaction, otherwise the test silently passes without ever running the handler.'],
  ['Event naming and payload','Past tense, immutable, carry ids rather than whole entities.','Why not put the JPA entity in the event? => it may be detached or lazily initialised by the time the handler runs, and it couples the consumer to your schema.']
 ],
 traps:[
  'Assuming @EventListener is asynchronous. It is not.',
  'Sending email or calling an external system from a plain @EventListener inside a transaction.',
  'A void @Async method with no exception handler - failures vanish silently.',
  'Publishing a JPA entity as the event payload, then hitting LazyInitializationException in the handler.',
  '@Scheduled running on every pod because nobody added a lock.'
 ]},

{id:'jpa', n:7, name:'JPA & Hibernate', phase:1, hrs:11,
 note:'The single richest source of "how does this actually work" questions at tier 1, because everyone claims it on a CV and few can explain the persistence context.',
 asked:[
  'What is the persistence context, and when does it flush?',
  'What is the N+1 problem and how do you detect it?',
  'You changed a field and never called save. Was it persisted?',
  'When does LazyInitializationException happen, and what is the right fix?'
 ],
 code:[
  ['The N+1 problem and three fixes',
   ['// N+1: one query for orders, then one per order for items',
    'List<Order> orders = orderRepo.findAll();',
    'orders.forEach(o -> o.getItems().size());     // N extra queries',
    '',
    '// FIX 1 - JOIN FETCH (best for a bounded result set)',
    '@Query("select distinct o from Order o join fetch o.items where o.status = :s")',
    'List<Order> findWithItems(@Param("s") Status s);',
    '',
    '// FIX 2 - entity graph, declarative',
    '@EntityGraph(attributePaths = "items")',
    'List<Order> findByStatus(Status status);',
    '',
    '// FIX 3 - batch fetching, best when combined with pagination',
    '@BatchSize(size = 50)   // on the collection',
    'private List<OrderItem> items;'],
   'Know all three and when each applies. JOIN FETCH plus pagination is a trap: Hibernate cannot paginate a fetched collection in SQL, so it silently loads everything into memory and pages in Java. @BatchSize is the correct answer there.'],
  ['Dirty checking - the thing that surprises people',
   ['@Transactional',
    'public void rename(Long id, String name) {',
    '    Order order = repo.findById(id).orElseThrow();',
    '    order.setName(name);',
    '    // no save() call - and it is still persisted',
    '}'],
   'Inside a transaction the entity is MANAGED. At commit, Hibernate compares it against the snapshot taken at load and issues an UPDATE. This is why an accidental setter inside a transaction writes to the database.'],
  ['Optimistic locking',
   ['@Entity',
    'public class Order {',
    '    @Id private Long id;',
    '    @Version private Long version;      // Hibernate manages this',
    '}',
    '',
    '// UPDATE orders SET ..., version = 3 WHERE id = ? AND version = 2',
    '// zero rows affected -> OptimisticLockException',
    '',
    '@Retryable(retryFor = OptimisticLockingFailureException.class, maxAttempts = 3)',
    '@Transactional',
    'public void applyDiscount(Long id, BigDecimal pct) { ... }'],
   'The version column turns a lost update into a detectable failure. Pair it with a retry, because the whole point is that a conflict is expected and recoverable.']
 ],
 qa:[
  ['The persistence context','A first-level cache and unit of work, scoped to the transaction. Entities inside it are managed.','Two findById calls for the same id in one transaction - how many queries? => one. The second is served from the persistence context.'],
  ['Entity states','Transient, managed, detached, removed.','What is a detached entity, and what breaks with one? => loaded in a transaction that has ended. Lazy fields throw, and save() will merge rather than update.'],
  ['Dirty checking','At flush, Hibernate diffs each managed entity against its load-time snapshot and generates UPDATEs.','You changed a field and never called save. Persisted? => yes, if inside a transaction. This is the most surprising JPA behaviour for newcomers.'],
  ['When does flush happen?','Before a query that might read affected tables, and at commit. FlushMode.AUTO by default.','Why might your INSERT appear earlier than you expected? => a query triggered an automatic flush.'],
  ['save vs saveAndFlush','save schedules; saveAndFlush forces SQL immediately.','When do you actually need saveAndFlush? => rarely. Usually when you need a generated id or a constraint violation before the transaction ends.'],
  ['The N+1 problem','One query for parents, then one per parent for the association.','How do you DETECT it? => enable hibernate statistics or datasource-proxy, or count queries in an integration test. Do not rely on spotting it in code review.'],
  ['LazyInitializationException','Touching a lazy association after the persistence context has closed.','What is the RIGHT fix? => fetch what you need inside the transaction with JOIN FETCH or an entity graph, or map to a DTO. Not open-in-view.'],
  ['open-in-view','Spring Boot keeps the persistence context open for the whole request. On by default.','Why is it harmful? => it holds a database connection for the entire request including view rendering, hides N+1 behind lazy loads, and exhausts the pool under load. Set spring.jpa.open-in-view=false and fix what breaks.'],
  ['FetchType.LAZY vs EAGER','Lazy by default for collections, eager for @ManyToOne and @OneToOne.','Why is eager on @ManyToOne a problem? => every load drags in the parent graph, and two eager collections produce a cartesian product.'],
  ['Cascade types','PERSIST, MERGE, REMOVE, ALL, plus orphanRemoval.','Why is CascadeType.ALL on @ManyToOne dangerous? => removing a child can delete the shared parent.'],
  ['orphanRemoval vs CascadeType.REMOVE','Orphan removal deletes a child removed from the collection; cascade remove deletes children when the parent is deleted.','Which one deletes on collection.remove(child)? => orphanRemoval.'],
  ['@OneToMany owning side','The side with the foreign key owns the relationship; use mappedBy on the inverse side.','You added to the collection and nothing persisted. Why? => you updated the inverse side only. Set both directions, or make the child set the parent.'],
  ['Optimistic locking with @Version','Version compared in the WHERE clause; zero rows affected means a conflict.','Two users edit the same row - walk me through it. => both read version 2, first commits and bumps to 3, second updates WHERE version = 2, affects zero rows, gets OptimisticLockException, retries.'],
  ['Pessimistic locking','@Lock(LockModeType.PESSIMISTIC_WRITE) issues SELECT FOR UPDATE.','When over optimistic? => high contention, where retrying would thrash.'],
  ['Entity equals/hashCode','Generated ids are null before persist, so identity changes after save.','Why does using the id in hashCode break a HashSet? => the object was added while transient with a null id, then the id changed. Use a natural key or a UUID assigned in the constructor.'],
  ['DTO projections','Select only the fields you need, via a constructor expression or an interface projection.','Why prefer this for read paths? => no persistence context overhead, no lazy loading surprises, and far less data over the wire.'],
  ['Second-level cache','Shared across transactions, opt-in per entity, needs a provider.','When is it a bad idea? => write-heavy entities, or a clustered deployment where invalidation is now a distributed problem.'],
  ['@Transactional(readOnly = true)','Skips dirty-check snapshots and may route to a replica.','Is it enforced? => no. It is an optimisation hint, not a guarantee.'],
  ['Spring Data derived queries','Method names parsed into queries: findByStatusAndCreatedAtAfter.','When do you stop using them? => once the name gets unreadable. Switch to @Query or a Specification.']
 ],
 traps:[
  'open-in-view left on, hiding N+1 and holding connections for the whole request.',
  'JOIN FETCH combined with pagination - silently loads everything into memory.',
  'Bidirectional relationship updated on one side only.',
  'Entity id used in hashCode before it is generated.',
  'CascadeType.ALL applied without thinking about deletes.'
 ]},

{id:'pg', n:8, name:'PostgreSQL', phase:1, hrs:9,
 note:'You are in DBeaver against upstream data daily, so this is claimed expertise and interviewers will test it.',
 asked:[
  'Read me this EXPLAIN plan.',
  'This query got slow after the table grew. Diagnose it.',
  'Why is your index not being used?',
  'Give me a lost update at READ COMMITTED.'
 ],
 code:[
  ['Reading a plan and fixing the index',
   ['EXPLAIN (ANALYZE, BUFFERS)',
    'SELECT * FROM orders WHERE status = \'PENDING\' AND created_at > now() - interval \'7 days\';',
    '',
    '-- Seq Scan on orders  (cost=0.00..18234 rows=100 width=64)',
    '--   (actual time=812ms rows=94512 loops=1)      <-- estimate 100, actual 94512',
    '',
    '-- equality column FIRST, range column SECOND',
    'CREATE INDEX CONCURRENTLY idx_orders_status_created',
    '    ON orders (status, created_at);',
    '',
    'ANALYZE orders;   -- refresh the statistics the planner uses'],
   'A large gap between estimated and actual rows means stale statistics, not a missing index. CONCURRENTLY avoids taking an exclusive lock on a live table - forgetting it is how people cause an outage.'],
  ['Queue in a table, done correctly',
   ['SELECT * FROM jobs',
    ' WHERE status = \'READY\'',
    ' ORDER BY created_at',
    ' LIMIT 10',
    '   FOR UPDATE SKIP LOCKED;'],
   'SKIP LOCKED lets N workers pull disjoint batches without blocking each other. Without it every worker queues behind the first, and your throughput is one worker regardless of how many you deploy.'],
  ['Zero-downtime column change',
   ['-- expand',
    'ALTER TABLE orders ADD COLUMN total_cents BIGINT;          -- nullable, instant',
    '-- migrate: backfill in batches, never one statement',
    'UPDATE orders SET total_cents = (total * 100)::bigint',
    ' WHERE id BETWEEN ? AND ? AND total_cents IS NULL;',
    '-- dual-write from the app, switch reads, then',
    '-- contract',
    'ALTER TABLE orders DROP COLUMN total;'],
   'Expand-migrate-contract. A single blocking ALTER on a 500M-row table takes an exclusive lock and stops the application. This is also why you cannot roll back a deploy that dropped a column.']
 ],
 qa:[
  ['B-tree index','Sorted and balanced. Supports equality, ranges, ordering, and the leftmost prefix of a composite.','Why does index column order matter? => leftmost-prefix. An index on (a,b) serves a and a+b, never b alone.'],
  ['Composite index design','Equality columns first, then the range column.','You have (status, created_at). Does a query on created_at alone use it? => not as a normal index scan.'],
  ['Covering / index-only scan','All required columns are in the index and the page is visible in the visibility map.','Why does VACUUM matter for index-only scans? => a stale visibility map forces a heap fetch and you lose the benefit.'],
  ['EXPLAIN ANALYZE','Actually runs the query. Compare estimated versus actual rows, and look at the node types.','Estimate says 10, actual is 94,512. What do you do? => ANALYZE, raise the statistics target, or rewrite a predicate the planner cannot estimate.'],
  ['When a sequential scan is correct','Low selectivity or a small table. Reading 40% of rows via an index is slower than a scan.','So why is an index sometimes slower? => random heap access plus index traversal beats a sequential read only when few rows match.'],
  ['MVCC','Every write creates a new row version; readers never block writers and writers never block readers.','Where do dead tuples go? => VACUUM reclaims them. If it cannot keep up you get bloat and the table grows without more data.'],
  ['Isolation levels','READ COMMITTED is the default; REPEATABLE READ gives a stable snapshot; SERIALIZABLE uses SSI and can abort transactions.','Give me a lost update at READ COMMITTED. => two transactions read balance 100, both compute 90, both write. One update is silently gone. Fix with an atomic UPDATE, SELECT FOR UPDATE, or a version column.'],
  ['SELECT FOR UPDATE','Row-level pessimistic lock held until the transaction ends.','What is SKIP LOCKED for? => queue workers pulling disjoint batches without blocking each other.'],
  ['Deadlocks','Two transactions acquiring the same rows in opposite order. Postgres detects and kills one.','How do you find and fix them? => the server log names both statements. Fix by ordering access consistently and shortening transactions.'],
  ['Connection pooling','HikariCP. Pool size around cores x 2, not hundreds.','The pool exhausted. Diagnose. => long transactions, leaked connections, N+1, open-in-view, or missing statement timeouts. A bigger pool usually makes it worse.'],
  ['Partial and expression indexes','CREATE INDEX ... WHERE status = \'ACTIVE\', or on lower(email).','Why does an index on email not help WHERE lower(email) = ? => the expression does not match the index. Index the expression.'],
  ['JSONB','Flexible documents with GIN indexing.','When does it become a mistake? => when you start querying and joining inside it. That is a schema asking to exist.'],
  ['Partitioning','Splitting one table by range or list within one database.','How is it different from sharding? => partitioning is one machine; sharding is many. Partitioning helps pruning and bulk deletes.'],
  ['CTEs and materialisation','Since Postgres 12 CTEs inline by default; MATERIALIZED forces the old behaviour.','Why did an old CTE query suddenly get faster on upgrade? => it stopped being an optimisation fence.'],
  ['Transaction length','Long transactions block VACUUM and hold connections.','Why is a transaction spanning an HTTP call to a third party a bug? => you hold a database connection and an MVCC snapshot for the duration of someone else network.'],
  ['UPSERT','INSERT ... ON CONFLICT (key) DO UPDATE.','Why is that better than check-then-insert? => check-then-insert is a race. ON CONFLICT is atomic.']
 ],
 traps:[
  'Building an index without CONCURRENTLY on a live table.',
  'Wrapping a column in a function and losing the index.',
  'A blocking ALTER TABLE on a large table during business hours.',
  'Assuming a bigger connection pool fixes exhaustion.',
  'Long transactions that hold snapshots and block VACUUM.'
 ]},

{id:'api', n:9, name:'REST, API design & auth', phase:2, hrs:7,
 asked:[
  'Design the API for this feature.',
  'Make this POST endpoint idempotent.',
  'How do you revoke a JWT?',
  'Your client retried and the customer was charged twice. Fix it.'
 ],
 code:[
  ['Idempotent POST',
   ['@PostMapping("/payments")',
    'public ResponseEntity<PaymentResponse> pay(',
    '        @RequestHeader("Idempotency-Key") String key,',
    '        @Valid @RequestBody PaymentRequest req) {',
    '',
    '    return idempotency.findByKey(key)',
    '        .map(prev -> ResponseEntity.ok(prev.response()))     // replay the stored result',
    '        .orElseGet(() -> {',
    '            PaymentResponse res = payments.charge(req);',
    '            idempotency.save(key, res);   // UNIQUE constraint on key',
    '            return ResponseEntity.status(CREATED).body(res);',
    '        });',
    '}'],
   'The unique constraint is what makes this correct under CONCURRENT retries - two simultaneous requests race, one insert wins, the other gets a constraint violation and can then read the winner result. A plain if-absent check is a race.'],
  ['Consistent error responses',
   ['@RestControllerAdvice',
    'public class ApiExceptionHandler {',
    '',
    '    @ExceptionHandler(MethodArgumentNotValidException.class)',
    '    ProblemDetail onValidation(MethodArgumentNotValidException ex) {',
    '        ProblemDetail pd = ProblemDetail.forStatus(BAD_REQUEST);',
    '        pd.setTitle("Validation failed");',
    '        pd.setProperty("errors", ex.getBindingResult().getFieldErrors().stream()',
    '                .collect(toMap(FieldError::getField, FieldError::getDefaultMessage)));',
    '        return pd;',
    '    }',
    '',
    '    @ExceptionHandler(OptimisticLockingFailureException.class)',
    '    ProblemDetail onConflict(Exception ex) {',
    '        return ProblemDetail.forStatusAndDetail(CONFLICT, "Resource was modified, retry");',
    '    }',
    '}'],
   'One error contract for the whole API. ProblemDetail (RFC 7807) is built into Spring 6 and is the answer if asked how you standardise errors.'],
  ['Cursor pagination',
   ['// offset: drifts when rows are inserted, and gets slower page by page',
    'GET /orders?page=5000&size=20',
    '',
    '// cursor: stable and O(log n) regardless of depth',
    'GET /orders?after=2026-08-27T10:00:00Z_01H9X&size=20',
    '',
    'SELECT * FROM orders',
    ' WHERE (created_at, id) < (:afterTs, :afterId)   -- tuple comparison',
    ' ORDER BY created_at DESC, id DESC',
    ' LIMIT 20;'],
   'Offset 100,000 makes the database count and discard 100,000 rows. The tuple comparison with a tiebreaker id is what makes the cursor deterministic.']
 ],
 qa:[
  ['Idempotency','The same request applied twice has the same effect as once. PUT and DELETE yes by definition, POST no.','How do you make POST idempotent? => a client-supplied Idempotency-Key with a unique constraint and a stored response, with a TTL.'],
  ['Status codes','201 with Location, 202 for accepted-async, 400 malformed, 422 semantically invalid, 409 conflict, 429 rate limited.','What do you return when processing is asynchronous? => 202 plus a status URL the client can poll.'],
  ['Pagination','Offset is simple but drifts and degrades; cursor is stable and fast.','Page 10,000 with offset - what is wrong? => the database materialises and discards everything before it.'],
  ['Versioning','URL path, custom header, or content negotiation.','How do you retire v1? => announce, measure usage per client, deprecation headers, then sunset. The hard part is organisational.'],
  ['PUT vs PATCH','Full replacement versus partial update.','Why is PATCH harder to get right? => merge semantics, null meaning "clear" versus "unchanged", and it is not naturally idempotent.'],
  ['OAuth2 flows','Authorization code with PKCE for user-facing apps; client credentials for service-to-service.','Why is the implicit flow deprecated? => the token is exposed in the URL fragment and there is no client authentication.'],
  ['JWT structure','header.payload.signature, base64url. Signed, not encrypted - anyone can read the payload.','So what must never go in a JWT? => anything secret. It is readable by the client.'],
  ['JWT revocation','You cannot revoke a stateless token before it expires.','So how do you handle logout? => short-lived access tokens plus a refresh token you can revoke, and a denylist of token ids for emergencies.'],
  ['Access vs refresh tokens','Short-lived credential versus long-lived means to obtain a new one.','Where do you store them in a browser? => refresh token in an httpOnly SameSite cookie; keeping either in localStorage exposes it to XSS.'],
  ['CORS','Browser-enforced preflight based on origin.','Does it protect your API? => no. It restricts browsers only. curl ignores it entirely.'],
  ['Rate limiting placement','At the gateway, before your service does work.','Per user or per IP? => both, at different tiers. Per IP alone punishes everyone behind a corporate NAT.'],
  ['Retries and backoff','Exponential with jitter, capped, only for idempotent operations.','What does retrying without jitter cause? => a thundering herd that keeps the downstream down.'],
  ['Timeouts','Every remote call needs one, and the budget must shrink down the chain.','Downstream p99 is 3s and your timeout is 5s. What happens under load? => your threads all block on the slow dependency and you fall over with it.'],
  ['Validation','Bean Validation annotations plus @Valid, handled centrally in @RestControllerAdvice.','Why validate in the DTO rather than the entity? => the API contract and the persistence model change for different reasons.'],
  ['API contract testing','OpenAPI spec generated or hand-written, plus contract tests.','How do you stop a breaking change reaching production? => compare the generated spec against the previous version in CI.']
 ],
 traps:[
  'A check-then-insert idempotency implementation, which races under concurrent retries.',
  'Returning 200 for everything, including errors.',
  'Leaking stack traces in error responses.',
  'Assuming CORS is a security control.',
  'No timeout on an outbound call.'
 ]}

]);


PLAN.tech = PLAN.tech.concat([

{id:'kafka', n:10, name:'Kafka', phase:2, hrs:13,
 note:'NEW KNOWLEDGE for you. Hands-on artefact required: Docker Compose with Kafka, a Spring Boot producer and consumer, a topic with 3 partitions, a consumer group of 2 - then KILL ONE CONSUMER and watch the rebalance, and REPLAY from an earlier offset. Reading about Kafka does not survive the follow-up column. Your custom Spring event components are the bridge: same problems, in-process.',
 asked:[
  'Where does Kafka actually guarantee ordering?',
  'Your consumer dies halfway through a batch. What happens?',
  'Kafka or RabbitMQ or SQS for this? Defend it.',
  'You built event-driven components yourself. Why not Kafka?'
 ],
 code:[
  ['Consumer with manual acknowledgement and a DLQ',
   ['@KafkaListener(topics = "orders", groupId = "invoicing",',
    '               containerFactory = "manualAckFactory")',
    'public void onOrder(ConsumerRecord<String, OrderEvent> rec, Acknowledgment ack) {',
    '    try {',
    '        // MUST be idempotent - at-least-once means this can run twice',
    '        invoices.createIfAbsent(rec.value().orderId(), rec.value());',
    '        ack.acknowledge();                 // commit only after success',
    '    } catch (TransientException e) {',
    '        throw e;                           // let the error handler retry',
    '    }',
    '}',
    '',
    '@Bean',
    'DefaultErrorHandler errorHandler(KafkaTemplate<String, Object> template) {',
    '    var recoverer = new DeadLetterPublishingRecoverer(template);   // -> orders.DLT',
    '    return new DefaultErrorHandler(recoverer,',
    '            new ExponentialBackOffWithMaxRetries(3));',
    '}'],
   'Commit AFTER processing, not before - that is the difference between at-least-once and at-most-once. The DLQ stops one poison message blocking the whole partition forever.'],
  ['Partition key controls ordering',
   ['// ordering is guaranteed PER PARTITION only',
    'kafkaTemplate.send("orders", order.customerId(), event);',
    '//                            ^^^^^^^^^^^^^^^^^ key -> partition',
    '',
    '// all events for one customer land on one partition, so they stay ordered',
    '// events for DIFFERENT customers may be processed out of order - usually fine'],
   'If you need per-entity ordering, the entity id is the key. And note the trap: adding partitions later changes the hash mapping, so existing keys move and ordering breaks across the boundary.'],
  ['Idempotent producer and transactions',
   ['spring:',
    '  kafka:',
    '    producer:',
    '      acks: all                        # wait for min.insync.replicas',
    '      enable-idempotence: true         # no duplicates on producer retry',
    '      transaction-id-prefix: tx-       # enables exactly-once within Kafka',
    '    consumer:',
    '      isolation-level: read_committed',
    '      enable-auto-commit: false        # you commit, not a timer',
    '      max-poll-records: 100'],
   'acks=all plus min.insync.replicas=2 is the durability setting for anything financial. Auto-commit is the default and it is wrong for almost everything - it commits on a timer regardless of whether you processed the record.']
 ],
 qa:[
  ['Topic, partition, offset','A topic is split into partitions; each partition is an ordered append-only log; consumers track an offset per partition.','Why partitions at all? => parallelism. Consumer parallelism is capped at the partition count.'],
  ['Ordering guarantee','Within a partition only. Never across a topic.','So how do you get per-user ordering? => partition key = user id. What breaks if you add partitions later? => the hash mapping changes and existing keys move.'],
  ['Consumer groups','Each partition is assigned to exactly one consumer within a group. Different groups each get everything.','3 partitions and 5 consumers in one group? => two sit idle. Adding consumers past the partition count buys nothing.'],
  ['Rebalancing','Any membership change reassigns partitions; processing pauses during it.','How do you avoid a rebalance storm? => raise max.poll.interval.ms if processing is slow, tune session timeout and heartbeats, and use the cooperative-sticky assignor.'],
  ['Consumer dies mid-batch','Offsets were not committed, so records are redelivered from the last commit.','So your consumer must be what? => idempotent. Say this before being asked.'],
  ['Delivery semantics','At-most-once commits first. At-least-once processes first - the default choice. Exactly-once needs the idempotent producer plus transactions.','Is exactly-once real? => within Kafka, yes. End to end, no - the moment you write to an external system you need idempotency there.'],
  ['auto-commit','Commits offsets on a timer whether or not you finished processing.','Why is enable.auto.commit=true dangerous? => a crash after the timer fires but before processing completes loses the record silently.'],
  ['Retention vs compaction','Retention deletes by time or size. Compaction keeps the latest value per key forever.','When do you compact? => changelog and state topics, where you want the current value of every key.'],
  ['Poison message','A record that always fails. Without handling it blocks its partition indefinitely.','Fix? => retry with backoff, then publish to a DLQ so the offset advances. Then a process to inspect and replay.'],
  ['Consumer lag','Log end offset minus committed offset.','Lag is growing. Name four causes. => slow processing, too few partitions, frequent rebalances, a slow downstream. Note CPU may look fine throughout.'],
  ['Kafka vs RabbitMQ vs SQS','Kafka is a durable replayable log with per-key ordering and consumer groups. RabbitMQ is a broker with rich routing and per-message ack. SQS is a managed queue with minimal operations.','Pick one for your event-driven components and defend it. => this is the question your background sets up.'],
  ['acks and min.insync.replicas','acks=0 fire and forget, acks=1 leader only, acks=all waits for the in-sync set.','Which for money? => acks=all with min.insync.replicas=2, and accept the latency.'],
  ['Schema evolution','A schema registry with backward and forward compatibility rules.','You add a required field. Who breaks? => existing consumers that do not know it. Add optional fields with defaults instead.'],
  ['Rebalance listeners','ConsumerRebalanceListener lets you commit before losing a partition.','Why does it matter? => without it, in-flight work on a revoked partition is redone by the new owner.'],
  ['Kafka Streams vs a plain consumer','Streams gives stateful processing, joins and windowing with a changelog-backed store.','When is a plain consumer enough? => stateless transformation and forwarding, which is most cases.'],
  ['From Spring events to Kafka','Spring events are in-process, synchronous by default, and lost on crash. Kafka is durable, replayable and cross-service.','When do you migrate? => when another service needs the event, when you need replay, or when losing one is unacceptable. The outbox is the migration path.']
 ],
 traps:[
  'Leaving auto-commit on.',
  'Assuming topic-wide ordering.',
  'No DLQ, so one bad record halts a partition forever.',
  'Adding partitions to a keyed topic without thinking about ordering.',
  'A non-idempotent consumer under at-least-once delivery.'
 ]},

{id:'micro', n:11, name:'Microservices & resilience', phase:2, hrs:9,
 note:'NEW KNOWLEDGE for you - you run a monolith. That is an ASSET here, not a gap: most candidates parrot microservices without ever having felt the pain. Being able to argue both sides is the strongest position in the room.',
 asked:[
  'Where would you split your monolith first, and why have you not?',
  'A downstream service is slow but not failing. What protects you?',
  'How do you keep a transaction consistent across two services?',
  'Argue against microservices.'
 ],
 code:[
  ['Circuit breaker, bulkhead, timeout and fallback',
   ['@CircuitBreaker(name = "pricing", fallbackMethod = "cachedPrice")',
    '@Bulkhead(name = "pricing")            // isolates the thread pool',
    '@TimeLimiter(name = "pricing")',
    '@Retry(name = "pricing")               // ONLY because this call is idempotent',
    'public CompletableFuture<Price> price(String sku) {',
    '    return CompletableFuture.supplyAsync(() -> pricingClient.get(sku));',
    '}',
    '',
    'private CompletableFuture<Price> cachedPrice(String sku, Throwable t) {',
    '    return CompletableFuture.completedFuture(cache.lastKnown(sku));',
    '}',
    '',
    '# resilience4j.circuitbreaker.instances.pricing:',
    '#   failureRateThreshold: 50',
    '#   waitDurationInOpenState: 10s',
    '#   permittedNumberOfCallsInHalfOpenState: 3'],
   'The order matters: Retry wraps CircuitBreaker wraps TimeLimiter wraps Bulkhead. A breaker without a timeout is useless, because a hang never counts as a failure - it just consumes threads.'],
  ['Strangler fig - how you actually split',
   ['// 1. put a facade in front of the monolith module',
    'interface PricingGateway { Price price(String sku); }',
    '',
    '// 2. implementation still calls in-process',
    'class InProcessPricing implements PricingGateway { ... }',
    '',
    '// 3. new implementation calls the extracted service',
    'class RemotePricing implements PricingGateway { ... }',
    '',
    '// 4. route by feature flag, percentage first, and compare outputs',
    '@Bean PricingGateway pricing(FeatureFlags flags) {',
    '    return flags.enabled("pricing.remote") ? remote : inProcess;',
    '}',
    '',
    '// 5. move the DATA last, once the seam has held for weeks'],
   'The interface comes first, the network call second, the data migration last. Teams that move the data first end up with a distributed monolith and no way back.']
 ],
 qa:[
  ['When NOT to use microservices','Small team, shared data model, unclear boundaries. They buy independent deploy and scale; they cost you a distributed system.','Argue against microservices. => answering this well is worth more than any architecture diagram. Distributed transactions, network partitions, versioned contracts, and debugging across five services.'],
  ['Splitting a monolith','Find a bounded context with few writes crossing the seam. Strangler-fig behind a facade. Move data last.','Which seam would you split first in YOUR system, and why have you not? => have a real answer ready.'],
  ['Distributed monolith','Services that must be deployed together. All the cost, none of the benefit.','How do you spot one? => a change requires coordinated releases, or one service being down takes all of them down.'],
  ['Service discovery','A registry, or Kubernetes Services plus DNS.','How does a caller find a healthy instance? => the Service only routes to pods passing readiness. That is discovery and health in one.'],
  ['API gateway','A single edge for auth, rate limiting, routing and aggregation.','The risk? => it accumulates business logic and becomes a deployment bottleneck.'],
  ['Circuit breaker','Closed, then open above a failure threshold, then half-open to probe.','A downstream is SLOW but not failing. What protects you? => a timeout first, then a bulkhead so it cannot exhaust your threads, then the breaker. A breaker alone never trips on slowness.'],
  ['Bulkhead','Isolate a thread pool or connection pool per dependency.','Why is a timeout not enough? => without isolation, enough slow calls still consume every request thread before any of them time out.'],
  ['Retries','Exponential backoff with jitter, only for idempotent operations.','You retried a payment. Now what? => a double charge, unless the endpoint takes an idempotency key.'],
  ['Saga','Local transactions plus compensating actions. Choreography (events) or orchestration (a coordinator).','Why not 2PC? => it holds locks across services for the duration of network calls and the coordinator is a single point of failure.'],
  ['Compensating transaction','A business-level undo, such as a refund - not a database rollback.','What if the step cannot be undone, like a sent email? => order the workflow so irreversible steps come last.'],
  ['Outbox','Write the row and the event in one local transaction; a relay publishes.','Why not write to the DB then publish? => the dual-write problem. If the publish fails, the systems silently diverge.'],
  ['Distributed tracing','A trace id propagated in headers, with a span per operation.','How does the id survive an async hop or a Kafka message? => a TaskDecorator copying the MDC, and trace headers on the Kafka record.'],
  ['Config and secrets','A config server, or Kubernetes ConfigMaps and Secrets.','How do you rotate a secret with zero downtime? => mounted files can be re-read; env vars require a restart. Design for the first.'],
  ['Data per service','Each service owns its store. No cross-service joins.','So how do you build a report spanning three services? => CQRS with a read model, an event-driven projection, or a warehouse. Not a shared database.'],
  ['Versioning service contracts','Additive changes only; never remove a field consumers still read.','How do you know who still reads it? => you instrument the field, or you cannot safely remove anything.'],
  ['Idempotency across services','Keys plus a dedup store, at every consumer.','Why is this non-negotiable? => at-least-once delivery means every handler runs twice eventually.']
 ],
 traps:[
  'A circuit breaker with no timeout - slowness never trips it.',
  'Retrying non-idempotent operations.',
  'Splitting the data before the interface.',
  'A shared database between services, which is a distributed monolith.',
  'No distributed tracing, so a cross-service latency problem is unfindable.'
 ]},

{id:'k8s', n:12, name:'Docker & Kubernetes', phase:1, hrs:11,
 note:'YOUR PRODUCTION EDGE. You run frontend and backend pods. Most candidates recite Kubernetes; you have been paged by it. Lead with a real incident.',
 asked:[
  'Your Java pod is OOMKilled. Walk me through it.',
  'What breaks if you swap liveness and readiness?',
  'Walk me through debugging CrashLoopBackOff.',
  'How do you deploy with genuinely zero downtime?'
 ],
 code:[
  ['Multi-stage build with a container-aware JVM',
   ['FROM maven:3.9-eclipse-temurin-21 AS build',
    'WORKDIR /app',
    'COPY pom.xml .',
    'RUN mvn -q dependency:go-offline        # cached layer - deps before source',
    'COPY src ./src',
    'RUN mvn -q clean package -DskipTests',
    '',
    'FROM eclipse-temurin:21-jre-alpine',
    'RUN addgroup -S app && adduser -S app -G app   # do not run as root',
    'USER app',
    'COPY --from=build /app/target/*.jar app.jar',
    '# the JVM must be told about the container limit',
    'ENTRYPOINT ["java","-XX:MaxRAMPercentage=75.0","-jar","/app.jar"]'],
   'Dependencies before source is what makes the layer cache work. MaxRAMPercentage is what stops the JVM sizing its heap from the NODE memory and getting OOMKilled.'],
  ['The deployment spec that actually gives zero downtime',
   ['spec:',
    '  strategy:',
    '    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }',
    '  template:',
    '    spec:',
    '      terminationGracePeriodSeconds: 45',
    '      containers:',
    '      - name: api',
    '        resources:',
    '          requests: { memory: "512Mi", cpu: "250m" }   # scheduler reserves',
    '          limits:   { memory: "1Gi" }                  # hard cap; NO cpu limit',
    '        readinessProbe:                                 # gates traffic',
    '          httpGet: { path: /actuator/health/readiness, port: 8080 }',
    '          periodSeconds: 5',
    '        livenessProbe:                                  # RESTARTS the container',
    '          httpGet: { path: /actuator/health/liveness, port: 8080 }',
    '          periodSeconds: 10',
    '          failureThreshold: 3',
    '        startupProbe:                                   # slow boot protection',
    '          httpGet: { path: /actuator/health/liveness, port: 8080 }',
    '          failureThreshold: 30',
    '        lifecycle:',
    '          preStop: { exec: { command: ["sh","-c","sleep 10"] } }'],
   'The preStop sleep is the piece almost everyone omits: endpoint removal and SIGTERM race, so without it the Service still routes to a pod that has started shutting down. Note also no CPU limit - requests for scheduling, limits only on memory, to avoid throttling.']
 ],
 qa:[
  ['Image layers','Copy-on-write layers; the cache invalidates from the first changed layer down.','How do you order a Dockerfile for cache hits? => dependencies before source, since source changes every build.'],
  ['Multi-stage builds','Build in a full image, copy only the artefact into a slim runtime.','Why does this matter beyond size? => attack surface. No compiler, no build tools, no shell in the shipped image.'],
  ['Pod vs container','A pod is the scheduling unit; containers in it share a network namespace and volumes.','When do two containers belong in one pod? => a sidecar tightly coupled in lifecycle, like a log shipper or a proxy.'],
  ['Deployment and ReplicaSet','You declare desired state; a controller reconciles continuously.','You deleted a pod. What happens? => the ReplicaSet creates a replacement. Deleting pods is not how you scale down.'],
  ['Service and Ingress','A Service is a stable virtual IP plus a label selector; Ingress is L7 routing into the cluster.','Walk me from a browser to a pod. => DNS, ingress controller, Service, kube-proxy or IPVS rules, pod IP.'],
  ['Liveness vs readiness vs startup','Liveness RESTARTS. Readiness REMOVES FROM ENDPOINTS. Startup delays liveness for slow boots.','What breaks if you swap them? => a pod that is briefly busy or waiting on a dependency gets killed instead of temporarily drained. Under load that becomes a cluster-wide restart loop.'],
  ['What liveness must not check','Downstream dependencies.','Why? => if the database is slow, every pod fails liveness and restarts simultaneously, turning a degradation into an outage.'],
  ['Requests vs limits','Requests are reserved by the scheduler; limits are the hard cap.','Set only limits - what happens? => requests default to limits, bin-packing gets worse and you waste capacity.'],
  ['OOMKilled','The container exceeded its memory limit; the kernel kills it. Exit code 137.','Your Java pod OOMKills. What do you change? => set MaxRAMPercentage so the heap respects the container, account for metaspace, thread stacks and direct buffers on top of heap, then take a heap dump and actually find the leak.'],
  ['CPU throttling','A CPU limit throttles via CFS quota rather than killing.','Latency spikes but memory is fine. What do you check? => container_cpu_cfs_throttled_seconds. Many teams remove CPU limits entirely and keep requests.'],
  ['CrashLoopBackOff','The container keeps exiting; restart delay grows exponentially.','Walk me through debugging it. => kubectl describe pod for events (image pull, mount, probe failures), then logs --previous for the last crash, then the exit code, then check config and secrets exist.'],
  ['Rolling update','maxSurge and maxUnavailable control the pace; readiness gates progress.','How do you get TRULY zero downtime? => readiness plus graceful shutdown plus a preStop drain plus backward-compatible schema. Missing any one drops requests.'],
  ['HPA','Scales replica count on CPU, memory or a custom metric.','You added HPA and it did not help. Why? => the bottleneck was the database, a connection pool or a single Kafka partition. More pods made it worse.'],
  ['ConfigMap vs Secret','Non-sensitive config versus base64-encoded values, which are NOT encrypted at rest by default.','How do you rotate without a restart? => mounted files update after a delay and can be re-read; env vars cannot change in a running process.'],
  ['StatefulSet','Stable network identity and per-pod persistent storage, ordered rollout.','Why not run Postgres in a Deployment? => no stable identity, no ordered startup, and volumes can attach to the wrong replica.'],
  ['Resource QoS classes','Guaranteed, Burstable, BestEffort - decided by your requests and limits.','Which pods get evicted first under node pressure? => BestEffort, then Burstable. Set requests if you want to survive.'],
  ['Init containers','Run to completion before app containers start.','A legitimate use? => waiting for a migration to complete, or fetching a config bundle.']
 ],
 traps:[
  'A JVM with no MaxRAMPercentage sizing its heap from node memory.',
  'Liveness probes that call the database.',
  'No preStop hook, so rolling updates drop in-flight requests.',
  'CPU limits causing invisible throttling.',
  'Treating Secrets as encrypted. They are base64 by default.'
 ]},

{id:'obs', n:13, name:'Observability, testing & CI/CD', phase:2, hrs:6,
 asked:[
  'How do you know this is broken before a customer tells you?',
  'How do you test a Kafka consumer?',
  'Why not H2 for integration tests?',
  'How do you roll back a bad deploy that included a schema change?'
 ],
 code:[
  ['Testcontainers - the real database in a test',
   ['@SpringBootTest',
    '@Testcontainers',
    'class OrderRepositoryTest {',
    '',
    '    @Container',
    '    static PostgreSQLContainer<?> pg = new PostgreSQLContainer<>("postgres:16");',
    '',
    '    @DynamicPropertySource',
    '    static void props(DynamicPropertyRegistry r) {',
    '        r.add("spring.datasource.url", pg::getJdbcUrl);',
    '        r.add("spring.datasource.username", pg::getUsername);',
    '        r.add("spring.datasource.password", pg::getPassword);',
    '    }',
    '}'],
   'The container is static, so it starts once for the whole class rather than per test. H2 accepts SQL Postgres rejects and lacks JSONB, window function edge cases and real locking behaviour - so H2-green, production-red is a familiar failure.'],
  ['Correlation id that survives an async hop',
   ['@Bean',
    'public TaskDecorator mdcDecorator() {',
    '    return runnable -> {',
    '        Map<String, String> ctx = MDC.getCopyOfContextMap();   // captured on the caller',
    '        return () -> {',
    '            if (ctx != null) MDC.setContextMap(ctx);',
    '            try { runnable.run(); } finally { MDC.clear(); }',
    '        };',
    '    };',
    '}',
    '// then: executor.setTaskDecorator(mdcDecorator());'],
   'Without this, every log line written on an @Async thread loses the trace id, and a cross-thread latency problem becomes unfindable. The finally clear matters because the thread is pooled.']
 ],
 qa:[
  ['Logs vs metrics vs traces','Discrete events, aggregated numbers, and the causal path of one request.','App is slow and you have all three. What first? => metrics to localise (which service, which endpoint, p99 vs p50), then traces for where the time went, then logs for the specific request. Cheapest to most expensive.'],
  ['Structured logging','JSON with consistent fields, including a correlation id.','How does the id survive an async hop or a Kafka message? => a TaskDecorator copying MDC, and trace headers on the record.'],
  ['What to alert on','User-visible symptoms and SLO burn rate.','Why is CPU above 80 percent a bad alert? => it is a cause, not a symptom, and it is often completely fine. Alerts that fire without user impact get ignored.'],
  ['Cardinality','The number of distinct label combinations on a metric.','Someone adds user_id as a Prometheus label. What happens? => one time series per user; memory and index blow up and the metrics system falls over.'],
  ['p50 vs p99','Median versus tail. Averages hide the tail entirely.','Why does p99 matter more? => on a page making 10 calls, a 1 percent tail affects roughly 10 percent of page loads.'],
  ['Test pyramid','Many fast unit tests, fewer integration, very few end-to-end.','Where do you test a repository query? => an integration test with a real database, via Testcontainers.'],
  ['Mockito','Mock collaborators, never the class under test.','When is mocking a smell? => mocking value objects, or asserting on interactions so specifically that any refactor breaks the test.'],
  ['Testcontainers vs H2','A real Postgres in Docker versus an in-memory imitation.','Why not H2? => dialect drift. H2 accepts SQL Postgres rejects, and lacks JSONB and real lock semantics, so tests pass and production fails.'],
  ['Testing a Kafka consumer','Testcontainers Kafka or an embedded broker for the wiring; call the handler directly for the logic.','What must you assert beyond the happy path? => that processing the same record twice is safe, since at-least-once guarantees it will happen.'],
  ['Testing @Transactional and events','Test transactions roll back by default, so AFTER_COMMIT listeners never fire.','So what happens to that test? => it silently passes without executing the handler. Use @Commit or TestTransaction.'],
  ['Flaky tests','Time, ordering, shared state, real network calls.','What do they cost? => the team stops trusting the suite, then stops reading failures, then ships the real bug.'],
  ['CI pipeline stages','Compile, unit, integration, build image, scan, deploy to staging, smoke, promote.','What should block a merge? => tests, coverage direction, and a dependency vulnerability scan.'],
  ['Blue-green vs canary','Two full environments with a switch, versus a percentage rollout.','Which for a schema change? => neither on its own. Schema needs expand-migrate-contract regardless of deployment strategy.'],
  ['Rollback','Redeploy the previous image. Schema changes must be backward compatible for that to work.','You dropped a column and need to roll back. Now what? => you cannot. Which is why contract is a separate later release from expand.'],
  ['Feature flags','Decouple deploy from release; roll out by percentage.','What is the hidden cost? => every flag is a branch in production, and stale flags accumulate into untested combinations.']
 ],
 traps:[
  'Alerting on causes instead of symptoms.',
  'High-cardinality metric labels.',
  'H2 in tests, Postgres in production.',
  'Tests that never exercise duplicate message delivery.',
  'Dropping a column in the same release that stops writing it.'
 ]}

]);


PLAN.techTriggers = [
  ['"our consumers keep falling behind"','Consumer lag · partition count · per-message processing time · rebalance frequency'],
  ['"the pod restarts under load"','Memory limit vs JVM heap · OOMKilled · MaxRAMPercentage · liveness probe too aggressive'],
  ['"it is slow but only sometimes"','GC pause · CPU throttling · connection-pool wait · p99 vs mean'],
  ['"the query got slow after the table grew"','Index column order · EXPLAIN · seq scan · stale statistics · bloat'],
  ['"the retry made it worse"','Thundering herd · no jitter · no circuit breaker · non-idempotent operation'],
  ['"the same request was processed twice"','At-least-once delivery · missing idempotency key · consumer died before commit'],
  ['"it works on my machine"','Image layers · env config · Testcontainers vs H2'],
  ['"two users overwrote each other"','Lost update · optimistic locking with @Version · isolation level'],
  ['"the transaction did not roll back"','Self-invocation · checked exception · caught and swallowed · wrong propagation'],
  ['"we cannot deploy without downtime"','Readiness probe · graceful shutdown · preStop · backward-compatible schema'],
  ['"the whole app went down because one service was slow"','Circuit breaker · bulkhead · timeout budget'],
  ['"we need to add a new consumer of this data"','Log-based stream over a queue · replay · compaction']
];

/* ============================================================== LINKING ===
   Problem rows link out to LeetCode and GeeksforGeeks.

   LeetCode slugs are derived from the title (lowercase, strip punctuation,
   hyphenate). That is correct for the large majority. Where a row bundles
   several problems under one heading, or the title was edited for the sheet,
   derivation would 404 - so those numbers get an explicit slug here.

   GfG has no problem numbers and its slugs carry an opaque numeric suffix
   that cannot be derived, so GfG links go through its search page. That
   always resolves. Where GfG names a problem differently from LeetCode, the
   better search term is given in PLAN.gfgName.                             */


PLAN.techRead = {
java:[['Baeldung — Java collections', 'https://www.baeldung.com/java-collections', 1],
      ['GfG — HashMap internal working', 'https://www.geeksforgeeks.org/internal-working-of-hashmap-java/', 1],
      ['Oracle — HotSpot garbage collection tuning', 'https://docs.oracle.com/en/java/javase/21/gctuning/', 1]],
modern:[['Baeldung — the Java 8 Stream API', 'https://www.baeldung.com/java-8-streams', 1],
        ['Oracle — records', 'https://docs.oracle.com/en/java/javase/21/language/records.html', 1],
        ['GfG — Optional class in Java', 'https://www.geeksforgeeks.org/java-8-optional-class/', 1]],
conc:[['Java Concurrency in Practice (the standard reference)', 'Java Concurrency in Practice Goetz happens-before', 0],
      ['Baeldung — the Java memory model and volatile', 'https://www.baeldung.com/java-volatile', 1],
      ['GfG — thread pools and ExecutorService', 'https://www.geeksforgeeks.org/thread-pools-java/', 1],
      ['Baeldung — CompletableFuture guide', 'https://www.baeldung.com/java-completablefuture', 1]],
spring:[['Spring Framework — the IoC container', 'https://docs.spring.io/spring-framework/reference/core/beans.html', 1],
        ['Spring — declarative transaction management', 'https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative.html', 1],
        ['Baeldung — why @Transactional self-invocation fails', 'https://www.baeldung.com/spring-transactional-propagation-isolation', 1]],
boot:[['Spring Boot — externalized configuration', 'https://docs.spring.io/spring-boot/reference/features/external-config.html', 1],
      ['Spring Boot — Actuator endpoints', 'https://docs.spring.io/spring-boot/reference/actuator/endpoints.html', 1],
      ['Spring Boot — graceful shutdown', 'https://docs.spring.io/spring-boot/reference/web/graceful-shutdown.html', 1]],
events:[['Spring Framework — application events', 'https://docs.spring.io/spring-framework/reference/core/beans/context-introduction.html#context-functionality-events', 1],
        ['Baeldung — Spring events and @TransactionalEventListener', 'https://www.baeldung.com/spring-events', 1],
        ['Baeldung — @Async in Spring', 'https://www.baeldung.com/spring-async', 1],
        ['Transactional outbox in Spring Boot', 'transactional outbox pattern spring boot implementation', 0]],
jpa:[['Vlad Mihalcea — the best JPA/Hibernate writing there is', 'https://vladmihalcea.com/tutorials/hibernate/', 1],
     ['Baeldung — the N+1 problem and how to fix it', 'https://www.baeldung.com/spring-data-jpa-n-plus-1', 1],
     ['Why you should disable open-in-view', 'Vlad Mihalcea open session in view anti-pattern', 0],
     ['Hibernate — fetching strategies', 'https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#fetching', 1]],
pg:[['PostgreSQL — using EXPLAIN', 'https://www.postgresql.org/docs/current/using-explain.html', 1],
    ['PostgreSQL — transaction isolation', 'https://www.postgresql.org/docs/current/transaction-iso.html', 1],
    ['Use The Index, Luke — index column order', 'https://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys', 1],
    ['PostgreSQL — routine vacuuming and bloat', 'https://www.postgresql.org/docs/current/routine-vacuuming.html', 1]],
api:[['RFC 7807 / RFC 9457 — problem details for HTTP APIs', 'https://www.rfc-editor.org/rfc/rfc9457.html', 1],
     ['Stripe — idempotent requests', 'https://docs.stripe.com/api/idempotent_requests', 1],
     ['OAuth 2.0 — authorization code flow with PKCE', 'https://oauth.net/2/pkce/', 1],
     ['AWS — exponential backoff and jitter', 'https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/', 1]],
kafka:[['Kafka — the official design document', 'https://kafka.apache.org/documentation/#design', 1],
       ['Confluent — consumer group rebalancing explained', 'https://www.confluent.io/blog/cooperative-rebalancing-in-kafka-streams-consumer-ksqldb/', 1],
       ['Spring for Apache Kafka reference', 'https://docs.spring.io/spring-kafka/reference/', 1],
       ['Exactly-once semantics in Kafka, and its limits', 'Kafka exactly once semantics transactions idempotent producer', 0]],
micro:[['Martin Fowler — MonolithFirst', 'https://martinfowler.com/bliki/MonolithFirst.html', 1],
       ['Martin Fowler — the strangler fig application', 'https://martinfowler.com/bliki/StranglerFigApplication.html', 1],
       ['Resilience4j documentation', 'https://resilience4j.readme.io/docs/getting-started', 1],
       ['Release It! — circuit breakers, bulkheads and timeouts', 'Release It Nygard stability patterns bulkhead circuit breaker', 0]],
k8s:[['Kubernetes — probes', 'https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/', 1],
     ['Kubernetes — resource requests and limits', 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/', 1],
     ['Docker — multi-stage builds', 'https://docs.docker.com/build/building/multi-stage/', 1],
     ['Kubernetes — pod termination and preStop', 'https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination', 1]],
obs:[['Google SRE Book — monitoring distributed systems', 'https://sre.google/sre-book/monitoring-distributed-systems/', 1],
     ['Testcontainers for Java', 'https://java.testcontainers.org/', 1],
     ['OpenTelemetry — signals', 'https://opentelemetry.io/docs/concepts/signals/', 1],
     ['Why H2 is a bad stand-in for Postgres in tests', 'H2 in memory database vs Testcontainers postgres dialect differences', 0]]
};


/* ============================================== CONCURRENCY PRACTICE ===
   Concurrency is asked as CODE at tier 1 (JPM, Amex, Goldman) and as a
   follow-up on design problems everywhere else. Reading about volatile does
   not survive "write me a bounded blocking queue".

   Keyed by tech module id so other modules can take problem sets later.
   Row: [lc, name, difficulty, note]  ·  lc null = no LeetCode equivalent,
   so the row links to a search instead.                                  */


PLAN.techProblems = {

conc: {
 intro:'LeetCode has a small, unloved Concurrency section that is exactly right for this — nine problems that force you to use wait/notify, semaphores and CountDownLatch correctly. Do all nine; they take an evening each at most. Then the classic implementations, which are what tier-1 interviews actually ask you to write on a whiteboard.',
 groups:[

  ['LeetCode · the Concurrency section — do all nine',
   'Small problems, but they will not compile until your synchronisation is genuinely correct. Solve each one twice: once with synchronized/wait/notify, once with a java.util.concurrent primitive. The comparison is the lesson.',
   [
    [1114,'Print in Order','E','Three threads, forced order. Start here. wait/notify first, then CountDownLatch — the second version should be half the length.'],
    [1115,'Print FooBar Alternately','M','Two threads alternating. The classic wait/notify ping-pong, or two Semaphores. Watch for the lost-wakeup bug.'],
    [1116,'Print Zero Even Odd','M','Three threads, a cycle rather than a pair. Semaphores make this clean; wait/notify with one lock gets ugly fast.'],
    [1117,'Building H2O','M','A barrier problem: two H for every O. Semaphore plus CyclicBarrier is the intended shape.'],
    [1195,'Fizz Buzz Multithreaded','M','Four threads on one counter. Good practice at deciding what the shared state actually is.'],
    [1226,'The Dining Philosophers','M','THE deadlock problem. Solve it three ways: global lock ordering, an arbitrator/semaphore limiting to n-1 diners, and tryLock with timeout. Be able to explain which Coffman condition each one breaks.'],
    [1188,'Design Bounded Blocking Queue','M','PREMIUM. The single most-asked concurrency implementation in real interviews. If you can only do one from this list, do this — and see the classics section below.'],
    [1242,'Web Crawler Multithreaded','M','PREMIUM. An ExecutorService plus a concurrent visited-set. The realistic one: a thread pool, not raw threads.'],
    [1279,'Traffic Light Controlled Intersection','E','PREMIUM. Simple mutual exclusion. Fine to skip if you cannot access it.']
   ]],

  ['Classic implementations — no LeetCode equivalent, and asked constantly',
   'These are whiteboard questions at JP Morgan, Amex, Goldman and most finance-adjacent loops. Write each from a blank file, then write a test that actually exercises the race with a CountDownLatch and 50 threads.',
   [
    [null,'Bounded blocking queue with wait/notify','M','put() waits while full, take() waits while empty. Must use while(...) wait() not if — spurious wakeups are the whole point. Then rewrite with ReentrantLock and two Conditions (notFull, notEmpty) and say why two conditions beat notifyAll.'],
    [null,'Producer-consumer with a bounded queue','M','The application of the above. Say out loud that the bound IS the backpressure mechanism.'],
    [null,'Readers-writers lock','H','Many readers or one writer. Then the follow-up nobody prepares: is it reader-preferring or writer-preferring, and which one starves? Compare against ReentrantReadWriteLock.'],
    [null,'A simple fixed thread pool','H','A BlockingQueue plus N worker threads looping on take(). Shows you understand what ExecutorService actually is. Follow-up: how does shutdown() differ from shutdownNow()?'],
    [null,'Implement a CountDownLatch from scratch','M','Around 15 lines with wait/notifyAll. Proves you understand the primitive rather than just calling it.'],
    [null,'Implement a Semaphore from scratch','M','Same idea, with permits. Then: why is acquire() in a while loop?'],
    [null,'Thread-safe singleton','E','Enum, holder idiom, and double-checked locking. Be ready to explain why DCL is BROKEN without volatile — the reference can be published before the constructor finishes.'],
    [null,'Reproduce a deadlock, then fix it','M','Two accounts, two threads, transfer in opposite directions. Fix by global lock ordering on the account id, then again with tryLock and timeout. Find it in a thread dump — jstack prints "Found one Java-level deadlock" explicitly.'],
    [null,'Thread-safe counter, three ways','E','synchronized, then AtomicInteger with a CAS loop, then LongAdder. Benchmark them under contention and be able to say when LongAdder wins.'],
    [null,'Rate limiter: token bucket, thread-safe','M','Lazy refill on access. Lock per bucket, never one global lock. This one bridges straight into the system design session.'],
    [null,'Print N numbers with N threads in order','M','Generalises 1114. A single lock plus a turn variable, or an array of Semaphores.'],
    [null,'Async fan-out with CompletableFuture','M','Ten remote calls in parallel, collect results, with a per-call timeout and fallback. Pass your OWN executor — never the common ForkJoinPool for IO.']
   ]],

  ['Design problems where concurrency IS the question',
   'These appear elsewhere in this sheet as design problems. Re-solve them here with thread safety as the primary requirement, because that is how the follow-up arrives in a real round.',
   [
    [146,'LRU Cache — now make it thread-safe','M','The interesting part: get() mutates the recency list, so a read is a write and it cannot be lock-free. Answer in three levels — global lock, segmented, then approximate LRU with read buffering (what Caffeine does).'],
    [1188,'Bounded blocking queue','M','PREMIUM. Listed twice on purpose. It is both a LeetCode problem and the classic whiteboard implementation.'],
    [362,'Design Hit Counter','M','PREMIUM. Add the concurrency follow-up yourself: many threads recording hits into time buckets.'],
    [359,'Logger Rate Limiter','E','PREMIUM. Make the message map concurrent, then handle the memory leak when messages are never evicted.'],
    [1279,'Traffic Light Controlled Intersection','E','PREMIUM. Mutual exclusion in its simplest form.'],
    [155,'Min Stack — make it thread-safe','E','Deceptive. Two structures must stay consistent, so per-method synchronized is not enough for compound operations.'],
    [295,'Find Median from Data Stream — concurrent','H','Two heaps that must be rebalanced atomically. A good test of where you put the lock.']
   ]]
 ],
 drill:[
  'Write a test that actually races. A CountDownLatch, 50 threads, all released at once, then assert the invariant. A concurrency implementation with no such test is unverified.',
  'Solve each problem twice — once with synchronized/wait/notify, once with java.util.concurrent. Interviewers ask "could you do that without synchronized?"',
  'Always use while(condition) wait(), never if(condition) wait(). Spurious wakeups are real and this is checked.',
  'Say where the lock is scoped. "Per bucket, not per limiter" or "per spot, not per lot" is the sentence that separates a correct answer from a good one.',
  'Run with -XX:+PrintCompilation or a thread dump at least once, so "how would you diagnose it in production" is not hypothetical.'
 ]
}

};

/* correct slugs for the LeetCode concurrency section */

export default PLAN;
